#!/usr/bin/env python3
import sys
from datetime import datetime
import subprocess

date = datetime.today().strftime('%Y-%m-%d')
title = sys.argv[1] if len(sys.argv) > 1 else 'x-x-x-x-x'
permalink_title = title.replace(' ', '-').lower() if len(sys.argv) > 1  else 'x'
bgcolor = sys.argv[2]  if len(sys.argv) > 2 else '#abc'
textColor = sys.argv[3] if len(sys.argv) > 3 else '#210'
links = sys.argv[4] if len(sys.argv) > 4 else '#f09'
hover = sys.argv[4] if len(sys.argv) > 4 else '#ff22ff'
alinks = sys.argv[5] if len(sys.argv) > 5 else '#f90'
vlinks = sys.argv[6] if len(sys.argv) > 6 else '#09f'
filename = '_posts/' + date + '-' + permalink_title + '.md'
template = '''\
---
title: {title}
date: {date}
author: 'Mike iLL'
layout: post
permalink: /{dateFormatted}/{permalink_title}
categories:
    - 'News'
og_description:
og_keywords:
---
'''
with open(filename, 'w') as new:
  new.write(template.format(
    title=title,
    permalink_title=permalink_title,
    date=date if date else 'No Date',
    dateFormatted=date.replace('-','/') if date else 'No Date',
    bgcolor=bgcolor,
    textColor=textColor,
    links=links,
    hover=hover,
    alinks=links,
    vlinks=links,
  ))
print('Created %s' % filename)
subprocess.Popen("open -a 'Visual Studio Code.app' " + filename, shell=True)
subprocess.Popen("git add " + filename, shell=True)
